package com.theseus.api.domain.chat.entity;

public enum ChatMessageType {
	CHAT,
	TOOL_PLAN_REQUEST,
	TOOL_PLAN_RESPONSE,
	TOOL_DRAFT_REQUEST,
	TOOL_DRAFT_RESPONSE,
	TOOL_FEEDBACK,
	TOOL_REGENERATE_RESPONSE,
	TOOL_APPROVAL_REQUEST,
	TOOL_BUILD_NOTICE,
	SYSTEM_NOTICE
}
