spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
  public-key-path: ${JWT_PUBLIC_KEY_PATH:classpath:keys/public_key.pem}
  issuer: ${JWT_ISSUER:core-api-server}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}

auth:
  refresh-cookie:
    secure: true
    same-site: Lax

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: info
    com.s14p21a503.coreapi.common.exception: debug
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: off
