services:
  nginx:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - stock-network

networks:
  stock-network:
    external: true
    name: stock-network
