services:
  theseus-api-server:
    build:
      context: ../../../backend/theseus-api-server
      dockerfile: Dockerfile
    image: theseus-api-server:local
    container_name: theseus-local-api-server
    env_file:
      - .env.local
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://theseus-local-mysql:3306/theseus
      SPRING_KAFKA_BOOTSTRAP_SERVERS: theseus-local-kafka:29092
      SPRING_DATA_REDIS_HOST: theseus-local-redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      theseus-local-mysql:
        condition: service_healthy
      theseus-local-kafka:
        condition: service_healthy
      theseus-local-redis:
        condition: service_healthy
    networks:
      - theseus-local-network

networks:
  theseus-local-network:
    name: theseus-local-network
