spring:
  cloud:
    gateway:
      routes:
        - id: core-api-route
          uri: http://localhost:8081 # core 서버 주소
          predicates:
            - Path=/api/v1/core/**
        - id: market-route
          uri: http://localhost:8083 # market 서버 주소
          predicates:
            - Path=/api/v1/market/**
        - id: core-api-docs
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/core-api
          filters:
            - RewritePath=/v3/api-docs/core-api, /v3/api-docs
        - id: market-api-docs
          uri: http://localhost:8083
          predicates:
            - Path=/v3/api-docs/market
          filters:
            - RewritePath=/v3/api-docs/market, /v3/api-docs

springdoc:
  swagger-ui:
    persist-authorization: true # 로그인 정보 유지용
    urls:
      - name: core-api
        url: /v3/api-docs/core-api
      - name: market
        url: /v3/api-docs/market
jwt:
  secret: ${JWT_SECRET_KEY}