spring:
  cloud:
    gateway:
      routes:
        - id: core-api-route
          uri: http://localhost:8081 # core 서버 주소
          predicates:
            - Path=/api/v1/core/**
        - id: market-route
          uri: http://localhost:8085 # market 서버 주소
          predicates:
            - Path=/api/v1/market/**
        - id: ai-route
          uri: http://localhost:8086 # ai 서버 주소
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - RewritePath=/api/v1/ai/(?<segment>.*), /v1/${segment}
        - id: core-api-docs
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/core-api
          filters:
            - RewritePath=/v3/api-docs/core-api, /v3/api-docs
        - id: market-api-docs
          uri: http://localhost:8085
          predicates:
            - Path=/v3/api-docs/market
          filters:
            - RewritePath=/v3/api-docs/market, /v3/api-docs
        # Gateway Routes에 추가
        - id: ai-api-docs
          uri: http://localhost:8086
          predicates:
            - Path=/v3/api-docs/ai
          filters:
            - RewritePath=/v3/api-docs/ai, /v3/api-docs
springdoc:
  swagger-ui:
    persist-authorization: true # 로그인 정보 유지용
    urls:
      - name: core-api
        url: /v3/api-docs/core-api
      - name: market
        url: /v3/api-docs/market
      - name: ai-api
        url: /v3/api-docs/ai
jwt:
  secret: ${JWT_SECRET_KEY}
